In [1]:
#import dependencies
import pandas as pd
from sqlalchemy import create_engine
import numpy as np

In [2]:
csv_file = "tv_shows.csv"
tv_shows_df = pd.read_csv(csv_file)
tv_shows_df.head()

,Unnamed: 0,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,type
0,0,Breaking Bad,2008,18+,9.5,96%,1,0,0,0,1
1,1,Stranger Things,2016,16+,8.8,93%,1,0,0,0,1
2,2,Money Heist,2017,18+,8.4,91%,1,0,0,0,1
3,3,Sherlock,2010,16+,9.1,78%,1,0,0,0,1
4,4,Better Call Saul,2015,18+,8.7,97%,1,0,0,0,1

In [3]:
show_df = tv_shows_df[['Title', 'Year', 'IMDb', 'Rotten Tomatoes', 'Netflix', 'Hulu', 'Prime Video', 'Disney+']]

In [4]:
show_df.head()

,Title,Year,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+
0,Breaking Bad,2008,9.5,96%,1,0,0,0
1,Stranger Things,2016,8.8,93%,1,0,0,0
2,Money Heist,2017,8.4,91%,1,0,0,0
3,Sherlock,2010,9.1,78%,1,0,0,0
4,Better Call Saul,2015,8.7,97%,1,0,0,0

In [5]:
# Change TV show providers to boolean values
show_df[['Netflix','Hulu', 'Prime Video', 'Disney+']] = show_df[['Netflix','Hulu', 'Prime Video', 'Disney+']].astype(bool)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]

In [6]:
show_df.head()

,Title,Year,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+
0,Breaking Bad,2008,9.5,96%,True,False,False,False
1,Stranger Things,2016,8.8,93%,True,False,False,False
2,Money Heist,2017,8.4,91%,True,False,False,False
3,Sherlock,2010,9.1,78%,True,False,False,False
4,Better Call Saul,2015,8.7,97%,True,False,False,False

In [7]:
show_df['Rotten Tomatoes'].isnull().sum().sum()

4600

In [8]:
show_df['IMDb'].isnull().sum().sum()

1161

In [9]:
#Replace missing values in Rotten Tomatoes column
show_df['Rotten Tomatoes'].fillna('00%', inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:6130: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [10]:
show_df['Rotten Tomatoes'].isnull().sum().sum()

0

In [11]:
#Replace missing values in IMDb column
show_df['IMDb'].fillna(0.0, inplace=True)

In [12]:
#Replace missing values in 
show_df['IMDb'].isnull().sum().sum()

0

In [13]:
show_df.dtypes

Title               object
Year                 int64
IMDb               float64
Rotten Tomatoes     object
Netflix               bool
Hulu                  bool
Prime Video           bool
Disney+               bool
dtype: object

In [14]:
rate_df = show_df
rate_df.head()

,Title,Year,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+
0,Breaking Bad,2008,9.5,96%,True,False,False,False
1,Stranger Things,2016,8.8,93%,True,False,False,False
2,Money Heist,2017,8.4,91%,True,False,False,False
3,Sherlock,2010,9.1,78%,True,False,False,False
4,Better Call Saul,2015,8.7,97%,True,False,False,False

In [20]:
rate_df.head()

,Title,Year,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+
0,Breaking Bad,2008,9.5,96%,True,False,False,False
1,Stranger Things,2016,8.8,93%,True,False,False,False
2,Money Heist,2017,8.4,91%,True,False,False,False
3,Sherlock,2010,9.1,78%,True,False,False,False
4,Better Call Saul,2015,8.7,97%,True,False,False,False

In [21]:
rate2df = rate_df

In [22]:
rate2df['Rotten Tomatoes'] = rate2df['Rotten Tomatoes'].replace({'%':''}, regex=True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [24]:
rate2df.head()

,Title,Year,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+
0,Breaking Bad,2008,9.5,96,True,False,False,False
1,Stranger Things,2016,8.8,93,True,False,False,False
2,Money Heist,2017,8.4,91,True,False,False,False
3,Sherlock,2010,9.1,78,True,False,False,False
4,Better Call Saul,2015,8.7,97,True,False,False,False

In [25]:
rate3df = rate2df

In [36]:
rate4df = rate2df

In [37]:
rate4df.head()

,Title,Year,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+
0,Breaking Bad,2008,9.5,96,True,False,False,False
1,Stranger Things,2016,8.8,93,True,False,False,False
2,Money Heist,2017,8.4,91,True,False,False,False
3,Sherlock,2010,9.1,78,True,False,False,False
4,Better Call Saul,2015,8.7,97,True,False,False,False

In [39]:
rate4df.dtypes

Title               object
Year                 int64
IMDb               float64
Rotten Tomatoes     object
Netflix               bool
Hulu                  bool
Prime Video           bool
Disney+               bool
dtype: object

In [41]:
rate4df['Rotten Tomatoes'] = rate4df['Rotten Tomatoes'].astype(str).astype(int)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [42]:
rate4df

,Title,Year,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+
0,Breaking Bad,2008,9.5,96,True,False,False,False
1,Stranger Things,2016,8.8,93,True,False,False,False
2,Money Heist,2017,8.4,91,True,False,False,False
3,Sherlock,2010,9.1,78,True,False,False,False
4,Better Call Saul,2015,8.7,97,True,False,False,False
5,The Office,2005,8.9,81,True,False,False,False
6,Black Mirror,2011,8.8,83,True,False,False,False
7,Supernatural,2005,8.4,93,True,False,False,False
8,Peaky Blinders,2013,8.8,92,True,False,False,False
9,Avatar: The Last Airbender,2005,9.2,100,True,False,False,False
10,The Walking Dead,2010,8.2,81,True,False,False,False
11,Dark,2017,8.7,94,True,False,False,False
12,Ozark,2017,8.4,81,True,False,False,False
13,Attack on Titan,2013,8.8,94,True,True,False,False
14,Narcos,2015,8.8,89,True,False,False,False
15,Fullmetal Alchemist: Brotherhood,2009,9.1,100,True,True,False,False
16,Community,2009,8.5,88,True,True,False,False
17,Mindhunter,2017,8.6,96,True,False,False,False
18,Parks and Recreation,2009,8.6,93,True,True,True,False
19,Dexter,2006,8.6,72,True,False,False,False
20,Marvel's Daredevil,2015,8.6,92,True,False,False,False
21,The Witcher,2019,8.3,67,True,False,False,False
22,Twin Peaks,1990,8.8,89,True,True,False,False
23,One-Punch Man,2015,8.8,100,True,True,False,False
24,Outlander,2014,8.4,91,True,False,False,False
25,House of Cards,2013,8.7,78,True,False,False,False
26,Shameless,2011,8.6,85,True,False,False,False
27,The Good Place,2016,8.2,97,True,True,False,False
28,The Haunting,2018,8.7,93,True,False,False,False
29,The Blacklist,2013,8.0,91,True,False,False,False
...,...,...,...,...,...,...,...,...
5581,Year Million,2017,7.5,0,False,False,False,True
5582,Origins: The Journey of Humankind,2017,6.7,0,False,False,False,True
5583,Bizaardvark,2016,3.5,0,False,False,False,True
5584,The Avengers: United They Stand,1999,5.5,0,False,False,False,True
5585,Spider-Woman,1979,5.7,0,False,False,False,True
5586,Dog: Impossible,2019,8.2,0,False,False,False,True
5587,America's National Parks,2015,7.9,0,False,False,False,True
5588,Kirby Buckets,2014,4.6,0,False,False,False,True
5589,LEGO Star Wars: All-Stars,2018,6.6,0,False,False,False,True
5590,Fast Layne,2019,5.4,0,False,False,False,True
5591,Teacher's Pet,2000,6.4,0,False,False,False,True
5592,Unlikely Animal Friends,2012,7.7,0,False,False,False,True
5593,Secrets of the Zoo: Tampa,2020,8.4,0,False,False,False,True
5594,Marvel Super Hero Adventures,2017,6.2,0,False,False,False,True
5595,Disney Family Sundays,2019,6.0,0,False,False,False,True
5596,Birth of Europe,2012,7.1,0,False,False,False,True
5597,Buried Secrets of the Bible with Albert Lin,2019,5.9,0,False,False,False,True
5598,Billy Dilley's Super-Duper Subterranean Summer,2017,4.6,0,False,False,False,True
5599,Rocky Mountain Animal Rescue,2018,7.8,0,False,False,False,True
5600,Prairie Dog Manor,2019,8.6,0,False,False,False,True
5601,Disney Junior Music Nursery Rhymes,2017,6.6,0,False,False,False,True
5602,Bug Juice: My Adventures at Camp,2018,7.2,0,False,False,False,True
5603,Disney Insider,2012,0.0,0,False,False,False,True
5604,Lost Treasures of the Maya,2019,0.0,0,False,False,False,True
5605,Awesome Animals,2013,0.0,0,False,False,False,True
5606,Tut's Treasures: Hidden Secrets,2018,0.0,0,False,False,False,True
5607,Paradise Islands,2017,0.0,0,False,False,False,True
5608,Wild Russia,2018,0.0,0,False,False,False,True
5609,Love & Vets,2017,0.0,0,False,False,False,True
5610,United States of Animals,2016,0.0,0,False,False,False,True

In [43]:
rate4df.dtypes

Title               object
Year                 int64
IMDb               float64
Rotten Tomatoes      int32
Netflix               bool
Hulu                  bool
Prime Video           bool
Disney+               bool
dtype: object

In [44]:
rate4df.to_csv(r'final_review.csv', index = False)